GAMEBOARD_SHEET_START_X = 324;
GAMEBOARD_SHEET_START_Y = 0;
GAMEBOARD_SHEET_WIDTH = 470;
GAMEBOARD_SHEET_HEIGHT = 137;
GAMEBOARD_CANVAS_START_X = 0;
GAMEBOARD_CANVAS_START_Y = 0;
GAMEBOARD_CANVAS_WIDTH = GAMEBOARD_SHEET_WIDTH;
GAMEBOARD_CANVAS_HEIGHT = GAMEBOARD_SHEET_HEIGHT;
MSPACMAN_SHEET_START_X = 83;
MSPACMAN_SHEET_START_Y = 20;
MSPACMAN_SHEET_WIDTH = 20;
MSPACMAN_SHEET_HEIGHT = 20;
MSPACMAN_CANVAS_START_X = 35;
MSPACMAN_CANVAS_START_Y = 30;
MSPACMAN_CANVAS_WIDTH = MSPACMAN_SHEET_WIDTH;
MSPACMAN_CANVAS_HEIGHT = MSPACMAN_SHEET_HEIGHT;

function init() {
	canvas = document.getElementById('game_canvas');
	if (canvas.getContext) {
		ctx = canvas.getContext('2d');
		sprite = new Image();
		sprite.src = 'pacman10-hp-sprite.png';
		sprite.onload = function() {
			ctx.drawImage(sprite, GAMEBOARD_SHEET_START_X,
				GAMEBOARD_SHEET_START_Y,
				GAMEBOARD_SHEET_WIDTH,
				GAMEBOARD_SHEET_HEIGHT,
				GAMEBOARD_CANVAS_START_X,
				GAMEBOARD_CANVAS_START_Y,
				GAMEBOARD_CANVAS_WIDTH,
				GAMEBOARD_CANVAS_HEIGHT);
			ctx.drawImage(sprite, MSPACMAN_SHEET_START_X,
				MSPACMAN_SHEET_START_Y,
				MSPACMAN_SHEET_WIDTH,
				MSPACMAN_SHEET_HEIGHT,
				MSPACMAN_CANVAS_START_X,
				MSPACMAN_CANVAS_START_Y,
				MSPACMAN_CANVAS_WIDTH,
				MSPACMAN_CANVAS_HEIGHT);
			audio = new Audio('start.mp3');
			audio.play();
		};
	}
	else {
		alert('Sorry, canvas is not supported on your browser!');
	}
}